# Generated by Django 5.2.6 on 2025-09-29 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mode',
            field=models.CharField(choices=[('secure', 'Secure Mode'), ('vulnerable', 'Vulnerable Mode')], default='secure', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vulnuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
