# Generated by Django 5.2.5 on 2025-09-22 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
