# Generated by Django 5.2.5 on 2025-09-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_securitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent identifier (e.g., pi_xxx)', max_length=100, null=True, unique=True),
        ),
    ]
