# Generated by Django 5.2.5 on 2025-10-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_intent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('secure', 'Secure'), ('vulnerable', 'Vulnerable')], max_length=20)),
                ('attack_type', models.CharField(blank=True, max_length=50, null=True)),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('ram_usage', models.FloatField(help_text='RAM usage in MB')),
                ('cpu_usage', models.FloatField(help_text='CPU usage percentage')),
                ('path', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
