# Generated by Django 5.2.5 on 2025-09-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('suricata_alert', 'Suricata Alert'), ('snort_alert', 'Snort Alert'), ('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scripting'), ('bruteforce', 'Brute Force'), ('other', 'Other')], default='other', max_length=50)),
                ('event_data', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action_taken', models.CharField(default='Logged', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('suricata_raw', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
