# Generated by Django 5.2.5 on 2025-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_incident_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='suricata_raw',
        ),
        migrations.AlterField(
            model_name='incident',
            name='attack_type',
            field=models.CharField(choices=[('suricata_alert', 'Suricata Alert'), ('snort_alert', 'Snort Alert'), ('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scripting'), ('bruteforce', 'Brute Force'), ('command_injection', 'Command Injection'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
